name: Waka Readme

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_a7acfb68-9e22-41d7-b193-a84180122c6c }}
          GH_TOKEN: ${{ secrets.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 }}
          LOCALE: "en"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_COMMIT: "True"
          SHOW_PROJECTS: "True"
          SHOW_DAYS_OF_WEEK: "True"
